# Generated by Django 5.2 on 2025-09-03 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workstations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workstation',
            options={'ordering': ['table_number'], 'verbose_name': 'Рабочее место', 'verbose_name_plural': 'Рабочие места'},
        ),
        migrations.RenameField(
            model_name='workstation',
            old_name='desk_number',
            new_name='table_number',
        ),
    ]
